#!/usr/bin/env python3
"""
Generate a deterministic battery of edge-case test documents for Posey.

The corpus is a stress test of Posey's normalization, segmentation, and
display pipelines. Each document targets ONE specific class of artifact
or content shape so regressions can be located precisely.

Output layout (default ~/.posey-corpus or --output-dir):
    txt/   plain-text edge cases
    md/    Markdown edge cases
    html/  HTML edge cases

Each file's name encodes what it tests, e.g. `txt/04_nbsp.txt`,
`txt/12_spaced_uppercase.txt`. The verification harness
(verify_synthetic_corpus.py) imports each file via the local API and
checks the post-normalization output for expected properties.

PDF, EPUB, and DOCX edge cases are generated by a sibling Swift script
(`generate_pdf_corpus.swift`) and an EPUB/DOCX zip helper, both of which
this Python script can invoke when --include-rich is passed.

Usage:
    python3 tools/generate_test_docs.py [--output-dir DIR] [--include-rich]
                                        [--formats txt,md,html,pdf,epub,docx]
                                        [--list]

Examples:
    # Generate everything to the default location
    python3 tools/generate_test_docs.py

    # Just TXT and MD
    python3 tools/generate_test_docs.py --formats txt,md

    # List planned generators without writing anything
    python3 tools/generate_test_docs.py --list

The generators are deterministic — running twice produces byte-identical
output. Safe to commit the corpus to a fixture repo or regenerate on CI.
"""
from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, List

DEFAULT_OUTPUT_DIR = Path.home() / ".posey-corpus"

# ----------------------------------------------------------------------
# Sentence stock — short, varied, deterministic. Reused across generators
# so the only variable is the artifact being tested, not the prose.
# ----------------------------------------------------------------------
PROSE_LINES = [
    "The reader settled into the chair and opened the book.",
    "Difficult prose rewards patience above all else.",
    "Notes anchored to the source remember themselves.",
    "Some sentences breathe; others gasp.",
    "The cadence of careful argument is itself an argument.",
    "When read aloud, prose finds its truer shape.",
    "A page of dense text is also a topography.",
    "The eye learns the page; the mind learns the thought.",
    "Reading is a conversation conducted across centuries.",
    "Footnotes are the marginalia of the disciplined.",
]

ARTIFACT_GENERATORS: List["DocSpec"] = []


@dataclass
class DocSpec:
    """One test document to generate."""
    fmt: str              # "txt" | "md" | "html" | "pdf" | "epub" | "docx"
    slug: str             # filename without extension; numeric prefix for ordering
    summary: str          # one-line description of what this document tests
    builder: Callable[[], bytes]   # returns raw bytes for the file

    @property
    def filename(self) -> str:
        return f"{self.slug}.{self.fmt}"


def register(spec: DocSpec) -> None:
    ARTIFACT_GENERATORS.append(spec)


# ======================================================================
# TXT-format generators
# ======================================================================

def _txt(content: str) -> bytes:
    return content.encode("utf-8")


def _txt_bom(content: str) -> bytes:
    return ("﻿" + content).encode("utf-8")


def _build_baseline_clean() -> bytes:
    return _txt("\n\n".join(PROSE_LINES) + "\n")


def _build_soft_hyphens() -> bytes:
    # U+00AD scattered through every word. Should be stripped to invisibility.
    soft = "­"
    text_lines = []
    for line in PROSE_LINES:
        out = []
        for word in line.split(" "):
            if len(word) >= 4:
                mid = len(word) // 2
                out.append(word[:mid] + soft + word[mid:])
            else:
                out.append(word)
        text_lines.append(" ".join(out))
    return _txt("\n\n".join(text_lines) + "\n")


def _build_line_break_hyphens() -> bytes:
    # Simulate PDF wrap: word ends with hyphen, next line starts with lowercase.
    # Should collapse to single word.
    pairs = [
        ("inde- pendent", "independent"),
        ("under- standing", "understanding"),
        ("trans- lation", "translation"),
        ("re- mark", "remark"),
        ("dem- onstration", "demonstration"),
    ]
    lines = []
    for src, _ in pairs:
        lines.append(f"The {src} of careful reading matters.")
    return _txt("\n\n".join(lines) + "\n")


def _build_logical_not_hyphens() -> bytes:
    # Some PDF generators use ¬ (U+00AC) as a line-break marker.
    pairs = [
        "indepen¬ dent",
        "under¬ standing",
        "trans¬ lation",
    ]
    lines = [f"Words like {p} are common in old typesetting." for p in pairs]
    return _txt("\n\n".join(lines) + "\n")


def _build_nbsp() -> bytes:
    # Non-breaking space ( ) between every word.
    nbsp = " "
    lines = [line.replace(" ", nbsp) for line in PROSE_LINES]
    return _txt("\n\n".join(lines) + "\n")


def _build_zwsp() -> bytes:
    # Zero-width space (​) inserted in random spots within words.
    zwsp = "​"
    lines = [line.replace("the", "th" + zwsp + "e") for line in PROSE_LINES]
    return _txt("\n\n".join(lines) + "\n")


def _build_bom() -> bytes:
    # BOM (﻿) at the file start.
    return _txt_bom("\n\n".join(PROSE_LINES) + "\n")


def _build_tabs() -> bytes:
    # Tabs everywhere instead of spaces.
    lines = [line.replace(" ", "\t") for line in PROSE_LINES]
    return _txt("\n\n".join(lines) + "\n")


def _build_mixed_line_endings() -> bytes:
    # Mix CRLF, CR, LF in the same file.
    parts = []
    for i, line in enumerate(PROSE_LINES):
        if i % 3 == 0:
            parts.append(line + "\r\n")
        elif i % 3 == 1:
            parts.append(line + "\r")
        else:
            parts.append(line + "\n")
    return "".join(parts).encode("utf-8")


def _build_trailing_whitespace() -> bytes:
    # Every line ends with trailing spaces and tabs.
    lines = [f"{line}   \t  " for line in PROSE_LINES]
    return _txt("\n\n".join(lines) + "\n")


def _build_excessive_blank_lines() -> bytes:
    # Many blank lines between paragraphs — should collapse to standard separator.
    return _txt(("\n" * 8).join(PROSE_LINES) + "\n")


def _build_spaced_uppercase() -> bytes:
    # PDF artifact: capitals separated by spaces.
    headings = ["C O N T E N T S", "I N T R O D U C T I O N", "C H A P T E R   O N E"]
    body = "\n\n".join(PROSE_LINES[:4])
    return _txt("\n\n".join(headings) + "\n\n" + body + "\n")


def _build_spaced_lowercase() -> bytes:
    headings = ["t a b l e   o f   c o n t e n t s", "p a g e   n u m b e r s"]
    body = "\n\n".join(PROSE_LINES[:4])
    return _txt("\n\n".join(headings) + "\n\n" + body + "\n")


def _build_spaced_accented() -> bytes:
    # Accented capitals — exercises the Unicode property class \p{Lu}.
    return _txt("P A S A R Á N\n\n" + "\n\n".join(PROSE_LINES[:4]) + "\n")


def _build_spaced_digits() -> bytes:
    # Digits separated by spaces (e.g. published years).
    lines = [
        "The book was written in 1 9 4 5 and revised in 1 9 6 7.",
        "Chapter 4 addresses 2 0 0 1 specifically.",
    ]
    return _txt("\n\n".join(lines) + "\n")


def _build_ligatures() -> bytes:
    # Unicode ligatures fi, fl, ffi.
    text = "The oﬃcial figure shows fiﬂtration is eﬃcient.\n\n"
    text += "fi: ﬁ fl: ﬂ ffi: ﬃ ffl: ﬄ\n"
    return _txt(text)


def _build_mixed_scripts() -> bytes:
    # English + Cyrillic + Greek + Arabic + CJK in the same paragraph.
    lines = [
        "The English word for 'book' is book.",
        "The Russian word is книга.",
        "The Greek word is βιβλίο.",
        "The Arabic word is كتاب.",
        "The Chinese word is 书.",
    ]
    return _txt("\n\n".join(lines) + "\n")


def _build_emoji() -> bytes:
    lines = [
        "The reader \U0001f4d6 settled into the chair \U0001fa91.",
        "Some sentences ✨ sparkle; others fade \U0001f4ad.",
    ]
    return _txt("\n\n".join(lines) + "\n")


def _build_combining_diacritics() -> bytes:
    # Same word with combining diacritic vs precomposed form.
    text = (
        "Café (precomposed)\n\n"  # U+00E9
        "Café (e + combining acute)\n\n"  # U+0065 + U+0301
        "These should look identical and read identically.\n"
    )
    return _txt(text)


def _build_rtl_mixed() -> bytes:
    text = (
        "The Arabic phrase مرحبا means hello.\n\n"
        "Hebrew שלום is also peace.\n"
    )
    return _txt(text)


def _build_empty() -> bytes:
    return b""


def _build_only_whitespace() -> bytes:
    return _txt("    \n\n\t\n  \n")


def _build_one_char() -> bytes:
    return _txt("A")


def _build_only_punctuation() -> bytes:
    # Tests segmenter behavior when there are no actual word characters.
    return _txt(". , ; : ! ? — – ... .,!?\n\n.,;:!?\n")


def _build_very_long_no_punct() -> bytes:
    # 2500-char "sentence" with no sentence-ending punctuation.
    word = "indistinguishable"
    text = (word + " ") * 130
    return _txt(text.strip() + "\n")


def _build_dot_leader_toc() -> bytes:
    # TOC with classic dot leaders: "Chapter 1 . . . . . 5"
    lines = [
        "Table of Contents",
        "",
        "Chapter 1 . . . . . . . . . . . . . . . . . 5",
        "Chapter 2 . . . . . . . . . . . . . . . . 23",
        "Chapter 3 . . . . . . . . . . . . . . . . 47",
        "Chapter 4 . . . . . . . . . . . . . . . . 71",
        "Index . . . . . . . . . . . . . . . . . . 95",
    ]
    return _txt("\n".join(lines) + "\n")


def _build_only_page_numbers() -> bytes:
    return _txt("1\n\n2\n\n3\n\n4\n\n5\n")


def _build_repeated_boilerplate() -> bytes:
    # Same watermark line repeated as if extracted from each PDF page.
    line = "(c) 2024 Example Press. All rights reserved."
    return _txt(("\n\n".join([line] * 20)) + "\n")


def _build_very_long_document() -> bytes:
    # ~100 KB of varied prose, paragraph-separated.
    body = "\n\n".join(PROSE_LINES * 200)
    return _txt(body + "\n")


def _build_unbalanced_quotes() -> bytes:
    # Smart quotes opened but not closed; mixed straight + curly.
    text = (
        "She said, “The text is broken,” and meant it.\n\n"
        "Then he replied: “Is it really? without closing the quote\n\n"
        "And finally a 'straight' “curly” mix.\n"
    )
    return _txt(text)


def _build_long_url() -> bytes:
    # Wayback-machine-style URL block — known pattern from the audit.
    url = "https://web.archive.org/web/20240101000000/https://example.com/very/long/path/to/an/article/that/has/many/segments?and=query&parameters=here&moreThings=true"
    text = f"Reference: {url}\n\nSee also: {url}\n"
    return _txt(text)


# Register TXT generators in deterministic order.
TXT_DOCS = [
    ("00_baseline_clean", "baseline; no edge cases", _build_baseline_clean),
    ("01_soft_hyphens", "U+00AD soft hyphens scattered in words", _build_soft_hyphens),
    ("02_line_break_hyphens", "PDF-style 'word- continuation' line wraps", _build_line_break_hyphens),
    ("03_logical_not_hyphens", "U+00AC ¬ as line-break marker", _build_logical_not_hyphens),
    ("04_nbsp", "U+00A0 non-breaking spaces between every word", _build_nbsp),
    ("05_zwsp", "U+200B zero-width spaces inside words", _build_zwsp),
    ("06_bom", "U+FEFF byte-order mark at file start", _build_bom),
    ("07_tabs", "tabs in place of spaces", _build_tabs),
    ("08_mixed_line_endings", "CRLF / CR / LF mixed in one file", _build_mixed_line_endings),
    ("09_trailing_whitespace", "trailing spaces and tabs on every line", _build_trailing_whitespace),
    ("10_excessive_blank_lines", "8 blank lines between paragraphs", _build_excessive_blank_lines),
    ("11_spaced_uppercase", "C O N T E N T S spaced-letter artifacts", _build_spaced_uppercase),
    ("12_spaced_lowercase", "lowercase spaced-letter artifacts", _build_spaced_lowercase),
    ("13_spaced_accented", "P A S A R Á N — accented capitals spaced", _build_spaced_accented),
    ("14_spaced_digits", "1 9 4 5 spaced-digit artifacts", _build_spaced_digits),
    ("15_ligatures", "Unicode ligatures fi/fl/ffi/ffl", _build_ligatures),
    ("16_mixed_scripts", "Latin/Cyrillic/Greek/Arabic/CJK mix", _build_mixed_scripts),
    ("17_emoji", "emoji embedded in prose", _build_emoji),
    ("18_combining_diacritics", "precomposed vs combining-mark forms", _build_combining_diacritics),
    ("19_rtl_mixed", "RTL substrings inside LTR prose", _build_rtl_mixed),
    ("20_empty", "completely empty file", _build_empty),
    ("21_only_whitespace", "only spaces, tabs, newlines", _build_only_whitespace),
    ("22_one_char", "single-character document", _build_one_char),
    ("23_only_punctuation", "only punctuation, no words", _build_only_punctuation),
    ("24_very_long_no_punct", "2500-char run with no sentence-ending punctuation", _build_very_long_no_punct),
    ("25_dot_leader_toc", "TOC with classic dot leaders", _build_dot_leader_toc),
    ("26_only_page_numbers", "just page numbers, no body", _build_only_page_numbers),
    ("27_repeated_boilerplate", "same watermark line repeated 20×", _build_repeated_boilerplate),
    ("28_very_long_document", "~100 KB of varied prose", _build_very_long_document),
    ("29_unbalanced_quotes", "unbalanced/mixed smart and straight quotes", _build_unbalanced_quotes),
    ("30_long_url", "Wayback-style very long URL block", _build_long_url),
]

for slug, summary, builder in TXT_DOCS:
    register(DocSpec("txt", slug, summary, builder))


# ======================================================================
# Markdown-format generators
# ======================================================================

def _build_md_clean() -> bytes:
    text = (
        "# Top heading\n\n"
        "## Subheading\n\n"
        + "\n\n".join(PROSE_LINES[:4])
        + "\n"
    )
    return _txt(text)


def _build_md_headings_only() -> bytes:
    text = (
        "# H1 alone\n\n"
        "## H2 alone\n\n"
        "### H3 alone\n\n"
        "#### H4 alone\n\n"
        "##### H5 alone\n\n"
        "###### H6 alone\n"
    )
    return _txt(text)


def _build_md_nested_lists() -> bytes:
    text = (
        "- One\n"
        "  - One.a\n"
        "    - One.a.i\n"
        "      - One.a.i.alpha\n"
        "  - One.b\n"
        "- Two\n"
        "- Three\n\n"
        "1. First numbered\n"
        "2. Second numbered\n"
        "   1. Nested numbered\n"
        "   2. Also nested\n"
        "3. Third numbered\n"
    )
    return _txt(text)


def _build_md_code_blocks() -> bytes:
    text = (
        "Inline `code` should be readable.\n\n"
        "```swift\n"
        "let answer = 42\n"
        "print(answer)\n"
        "```\n\n"
        "    indented code block\n"
        "    on multiple lines\n"
    )
    return _txt(text)


def _build_md_blockquote_nested() -> bytes:
    text = (
        "> Outer quote.\n"
        ">\n"
        "> > Nested quote.\n"
        "> >\n"
        "> > > Deeply nested.\n"
    )
    return _txt(text)


def _build_md_inline_html() -> bytes:
    text = (
        "Some <em>inline</em> HTML and a <a href=\"https://example.com\">link</a>.\n\n"
        "<div>A block of HTML with <strong>nested</strong> tags.</div>\n"
    )
    return _txt(text)


def _build_md_with_artifacts() -> bytes:
    # A markdown document carrying the same artifacts as PDFs.
    soft = "­"
    nbsp = " "
    text = (
        "# Sof" + soft + "t hyphens in heading\n\n"
        "Body with non-breaking" + nbsp + "spaces and" + nbsp + "more" + nbsp + "of them.\n\n"
        "## Spaced letters: T H I S   I S   I T\n\n"
        "Ligatures: oﬃcial floﬂed.\n"
    )
    return _txt(text)


MD_DOCS = [
    ("00_md_clean", "baseline markdown with heading + body", _build_md_clean),
    ("01_md_headings_only", "all six heading levels, no body", _build_md_headings_only),
    ("02_md_nested_lists", "nested bullets and numbered lists", _build_md_nested_lists),
    ("03_md_code_blocks", "fenced + indented code blocks", _build_md_code_blocks),
    ("04_md_blockquote_nested", "nested blockquotes (3 levels)", _build_md_blockquote_nested),
    ("05_md_inline_html", "inline HTML mixed with markdown", _build_md_inline_html),
    ("06_md_with_artifacts", "soft hyphens + nbsp + spaced letters in markdown", _build_md_with_artifacts),
]

for slug, summary, builder in MD_DOCS:
    register(DocSpec("md", slug, summary, builder))


# ======================================================================
# HTML-format generators
# ======================================================================

def _wrap_html(body: str, lang: str = "en") -> str:
    return (
        f"<!DOCTYPE html>\n<html lang=\"{lang}\">\n<head>\n"
        f"<meta charset=\"UTF-8\">\n<title>Test</title>\n</head>\n"
        f"<body>\n{body}\n</body>\n</html>\n"
    )


def _build_html_clean() -> bytes:
    body = "<h1>Title</h1>\n" + "\n".join(f"<p>{line}</p>" for line in PROSE_LINES[:4])
    return _txt(_wrap_html(body))


def _build_html_no_paragraphs() -> bytes:
    # All text crammed into one block with <br> instead of <p>.
    body = "<br>".join(PROSE_LINES)
    return _txt(_wrap_html(body))


def _build_html_inline_styles() -> bytes:
    body = (
        "<p>Some <strong>bold</strong>, <em>italic</em>, and "
        "<u>underlined</u> text.</p>\n"
        "<p>Also <span style=\"color: red;\">colored</span> spans.</p>"
    )
    return _txt(_wrap_html(body))


def _build_html_table() -> bytes:
    body = (
        "<h2>Data</h2>\n<table>\n"
        "<tr><th>Name</th><th>Value</th></tr>\n"
        "<tr><td>Alpha</td><td>1</td></tr>\n"
        "<tr><td>Beta</td><td>2</td></tr>\n"
        "</table>"
    )
    return _txt(_wrap_html(body))


def _build_html_with_script() -> bytes:
    body = (
        "<p>Visible text.</p>\n"
        "<script>alert('should not be read');</script>\n"
        "<p>More visible text.</p>\n"
        "<style>body { color: red; }</style>\n"
    )
    return _txt(_wrap_html(body))


def _build_html_entities() -> bytes:
    body = (
        "<p>HTML entities: &amp; &lt; &gt; &quot; &apos; &nbsp; &mdash; &hellip;</p>\n"
        "<p>Numeric refs: &#169; &#8482; &#x2764;</p>"
    )
    return _txt(_wrap_html(body))


def _build_html_deeply_nested() -> bytes:
    inner = "deep"
    for _ in range(20):
        inner = f"<div>{inner}</div>"
    return _txt(_wrap_html(inner))


HTML_DOCS = [
    ("00_html_clean", "baseline html with h1 + paragraphs", _build_html_clean),
    ("01_html_no_paragraphs", "no <p> tags, only <br> separators", _build_html_no_paragraphs),
    ("02_html_inline_styles", "bold / italic / underline / colored spans", _build_html_inline_styles),
    ("03_html_table", "simple table — exercises tabular extraction", _build_html_table),
    ("04_html_with_script", "<script> and <style> blocks should be stripped", _build_html_with_script),
    ("05_html_entities", "HTML entities and numeric character refs", _build_html_entities),
    ("06_html_deeply_nested", "20-level deep <div> nesting", _build_html_deeply_nested),
]

for slug, summary, builder in HTML_DOCS:
    register(DocSpec("html", slug, summary, builder))


# ======================================================================
# RTF-format generators
# ======================================================================

def _build_rtf_clean() -> bytes:
    text = (
        "{\\rtf1\\ansi\\deff0 {\\fonttbl{\\f0 Helvetica;}}\n"
        "\\f0\\fs28 The reader settled into the chair.\\par\n"
        "Difficult prose rewards patience.\\par\n"
        "}"
    )
    return _txt(text)


def _build_rtf_with_styles() -> bytes:
    text = (
        "{\\rtf1\\ansi\\deff0 {\\fonttbl{\\f0 Helvetica;}}\n"
        "\\f0\\fs36\\b Bold heading\\b0 \\par\n"
        "\\fs24 Body text follows.\\par\n"
        "\\i Italic emphasis\\i0 ends here.\\par\n"
        "}"
    )
    return _txt(text)


RTF_DOCS = [
    ("00_rtf_clean", "baseline RTF with text only", _build_rtf_clean),
    ("01_rtf_styled", "RTF with bold/italic styling", _build_rtf_with_styles),
]

for slug, summary, builder in RTF_DOCS:
    register(DocSpec("rtf", slug, summary, builder))


# ======================================================================
# CLI
# ======================================================================

def _selected_specs(formats: List[str]) -> List[DocSpec]:
    if not formats:
        return ARTIFACT_GENERATORS
    return [s for s in ARTIFACT_GENERATORS if s.fmt in formats]


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR,
                        help=f"where to write the corpus (default: {DEFAULT_OUTPUT_DIR})")
    parser.add_argument("--formats", default="",
                        help="comma-separated subset of formats to generate (txt,md,html,rtf,...). Empty = all.")
    parser.add_argument("--list", action="store_true",
                        help="list every spec without writing files")
    args = parser.parse_args(argv)

    formats = [f.strip().lower() for f in args.formats.split(",") if f.strip()]
    specs = _selected_specs(formats)

    if args.list:
        by_fmt: Dict[str, List[DocSpec]] = {}
        for s in specs:
            by_fmt.setdefault(s.fmt, []).append(s)
        for fmt in sorted(by_fmt):
            print(f"\n[{fmt}] ({len(by_fmt[fmt])} docs)")
            for s in by_fmt[fmt]:
                print(f"  {s.filename:40} {s.summary}")
        return 0

    if not specs:
        print(f"No generators match formats={formats!r}", file=sys.stderr)
        return 2

    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    written = 0
    for spec in specs:
        sub = out / spec.fmt
        sub.mkdir(exist_ok=True)
        target = sub / spec.filename
        target.write_bytes(spec.builder())
        written += 1
        print(f"  wrote {target.relative_to(out)}  ({spec.summary})")

    print(f"\nDone — {written} documents in {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
